[package]
name = "parallel_max_product_3_numbers"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon="*"
diam={git="https://github.com/wagnerf42/diam", branch="main"}
rand="*"
itertools="*"
